---
version: '3'
services:
  kibana:
    image: "docker.elastic.co/kibana/kibana:$KIBANA_VERSION"
    # https://www.elastic.co/guide/en/kibana/6.8/docker.html
    # https://github.com/elastic/dockerfiles
    # https://www.docker.elastic.co/
    env_file: config/kibana.env
    environment:
      SERVER_BASEPATH: /_plugin/kibana     # aws Elasticsearch と同じにしておく
      SERVER_REWRITEBASEPATH: 'true'
    network_mode: host
