---
version: '3'
services:
  kibana:
    image: "docker.elastic.co/kibana/kibana:$KIBANA_VERSION"
    # https://www.elastic.co/guide/en/kibana/6.8/docker.html
    # https://github.com/elastic/dockerfiles
    # https://www.docker.elastic.co/
    environment:
      # SERVER_HOST: '127.0.0.1'
      SERVER_BASEPATH: /_plugin/kibana     # aws Elasticsearch と同じにしておく
      SERVER_REWRITEBASEPATH: 'true'
      # ELASTICSEARCH_HOSTS: $ELASTICSEARCH_HOSTS
      XPACK_MONITORING_UI_CONTAINER_ELASTICSEARCH_ENABLED: 'false'
      # LOGGING_QUIET: 'true'
    extra_hosts:
      - 'elasticsearch:$ELASTICSEARCH_HOST'
    network_mode: host
